Added fortune command
Shotbow/ChatBot pull request #32
Opened 2018-06-03 19:57 UTC by BananaPuncher714

I've added a `!fortune` command that will display a random fortune set in the locale files. The fortunes are stored with the "fortunes" key, and are split with the '\n' character.

2018-06-03 22:14 UTC, McJeffr commented
Some pieces of feedback (some of which Navarr also had on my PRs):
- Make sure that all files end with LF. (See Command/Fortune.js)
- Make sure that all lines of code are indented with spaces. (See Command/Fortune.js and all localisation files)
- In general, try to be consistent with the style of the rest of the code (spaces between brackets and code, single and double quotations, indentation, etc.)
- The translation files are probably not correct this way. If a language is missing a value for a key, it falls back to display the key. In this case, this would mean that "fortunes" is simply displayed when a key doesn't exist. This is also the reason why all the messages in the localisation files are seemingly "double". My suggestion would be to store the fortunes in an array in the config files instead, and read them from there and pass that value on to the __mf() function. From there, all the fortunes would be registered independently on the localisation files.

As for the functional benefit of this command, I am not so sure about it. It would require a lot of work from the localisation team to translate the fortunes to their respective languages. But that's not up to me to decide.

2018-06-04 02:17 UTC, JamsheedMistri commented
As @McJeffr mentioned, please be consistent with the formatting. This would also be hard to translate. Finally, I don't see the point in this command.

2018-06-04 08:32 UTC, McJeffr commented
I would also quickly want to add that this code will crash the bot because pt_BR and ja JSON files are invalid because of a missing comma. GitHub also highlights this.

2018-06-04 13:15 UTC, BananaPuncher714 commented
Ok, I just thought that a fortune command would be interesting and keep chat somewhat more alive. I didn't intend for the fortunes to be the same for every language, seeing as different messages would be interpreted differently by different people. I'll be more consistent with the formatting if you should decide that this is an idea worth pursuing.

2018-06-10 15:15 UTC, navarr requested changes
The biggest issues here are the abuse of the localisation system for pulling in the fortunes and the non-matching codestyle.

If you want locale-specific fortunes, my recommendation is making an entry in the global config  fortunes with keys for languages

2018-06-10 15:15 UTC, navarr commented on src/Command/Fortune.js
> +    commandName: 'fortune',
As this is a "fun" command, it must include `advertisable: false,` so that it does not show up in help commands.

Our goal is to be helpful.  While I'm not opposed to fun, I don't want them hogging space that can be utilized by utility

2018-06-29 21:31 UTC, JamsheedMistri commented
@BananaPuncher714 If you don't intend to continue this, please close the PR.

2018-06-30 13:48 UTC, closed without merging