Added maximum length to amount of history entries being displayed.
Shotbow/ChatBot pull request #57
Opened 2020-04-21 23:33 UTC by McJeffr

This might be a fix to issue #56, but I am unsure as I was unable to replicate the bug. Either way, this cuts down very long lists (that can get quite spammy) into only 10 entries at max.

2020-04-22 12:07 UTC, navarr requested changes
Simply cutting off could be confusing to the players.

Would it be possible to add a message when it is cutoff and include a link to NameMC for the full history?

2020-04-22 12:41 UTC, McJeffr commented
> Simply cutting off could be confusing to the players.
> 
> Would it be possible to add a message when it is cutoff and include a link to NameMC for the full history?

Ah yeah, I can do this later today when I get "back" from work.

2020-04-22 22:42 UTC, McJeffr commented on src/Command.js
> -                    done();
The function "done" doesn't exist anywhere in this context. It threw errors about it not existing when I caused this promise to throw an error.

2020-05-13 14:18 UTC, navarr approved these changes

2020-05-15 03:06 UTC, merged