Added auto-closing functionality
Shotbow/ChatBot pull request #86
Opened 2020-08-19 23:11 UTC by McJeffr

Additionally, cleaned up some duplicate code that would be created as a result of this new feature.

The new configuration options are as follows:
```
    support: {
        autoClose: {
            warning: 2 * 24 * 60 * 60 * 1000,
            closing: 2 * 24 * 60 * 60 * 1000
        }
    },
```
Here, `warning` refers to the amount of time to pass by before a warning notice is being sent to the channel. This means that if the previous message was `warning` ms ago, a warning notice will be posted. This timer "resets" when someone else posts a message in the channel. The `closing` refers to the amount of time to pass by **after the warning message** in ms before the channel gets automatically closed. If someone posts a message, this timer "resets" as the last message must be the warning notice for this to take affect.

2020-08-19 23:17 UTC, McJeffr commented on src/Command/Support.js
> -                return await this.processDeletion(message, commandParameters);
Unsure what "commandParameters" even did here, the `processDeletion` function didn't even require this.

2020-08-20 17:35 UTC, navarr commented on config/default.js
> +            warning: 2 * 24 * 60 * 60 * 1000,
```suggestion
            warning: 1 * 24 * 60 * 60 * 1000,
```

2020-08-21 12:25 UTC, navarr requested changes

2020-08-21 12:25 UTC, navarr commented on src/Utility/SupportCloser.js
> +                console.log("WARNING: could not retrieve support category for automatic support closer utility");
```suggestion
                console.warn("Warning: Could not retrieve support category for automatic support closer utility");
```

2020-08-21 12:25 UTC, navarr commented on src/Command/Support.js
> +const { generateRoomName, parseRoomType, convertRoom, archiveRoom } = require('../Helper/SupportRoomHelper');
I think only archiveRoom is shared right?  Why not have it be its own helper (SupportRoomArchiver) and leave the others as functions in this file?

IMO, SupportRoomHelper is violating the SRP

2020-08-21 12:32 UTC, McJeffr commented on src/Command/Support.js
> +const { generateRoomName, parseRoomType, convertRoom, archiveRoom } = require('../Helper/SupportRoomHelper');
parseRoomType and getRoomParticipants are used by archiveRoom. The archiving of a room uses these two functions. I could move it to a SupportRoomArchiver, but there won't really be any functions left in SupportRoomHelper other than the name conversion (which uses generateRoomName). I don't think the SRP is broken here, these are all functions directly involved with support rooms (either archiving or converting, but the functions used for these two are shared among each of these two functions).

2020-08-21 12:58 UTC, navarr commented on src/Command/Support.js
> +const { generateRoomName, parseRoomType, convertRoom, archiveRoom } = require('../Helper/SupportRoomHelper');
If parseRoomType and getRoomParticipants are used by both archiveRoom and the Support command general functionality, they should be split out into their own classes/files.

What you've done here is create a container for support-related commands, and while that helps clean up the Support command file, by itself its messy.  There's no harm in breaking these out into their own files, which is what I'd recommend here.

* SupportRoomArchiver
* SupportRoomConverter
* SupportRoomTypeParser
* SupportRoomNameGenerator

All of those would serve a single purpose that its name clearly details, and you wouldn't have weird reverse mapping like `const { a, b, c }`

2020-08-21 14:08 UTC, McJeffr commented on src/Command/Support.js
> +const { generateRoomName, parseRoomType, convertRoom, archiveRoom } = require('../Helper/SupportRoomHelper');
Alright, that could work too. I'll look into it when I have time later today.

2020-08-23 20:39 UTC, navarr approved these changes

2020-08-23 20:39 UTC, merged